### ISSUE TITLE
ImportError: cannot import name 'AnswerParser' from 'parser' (unknown location)

### ISSUE THREAD

**Issue by Zanepin** [xll-1994/Spider-Collection#1]
均按照readme.md中的步骤配置
运行环境为Windows 10
似乎是parser.py重名的问题
请教一下如何解决。

**Comment by Zanepin** [comment]
env\Lib\site-packages\pip\_internal\cli\parser.py
env\Lib\site-packages\click\parser.py
两个路径下均有parser.py

**Comment by xll-1994** [comment]
是的，重名了。项目里有一个名称是parser的文件夹，我之前用pycharm运行的，所以没报错。需要修改下文件夹名及相关引用。

**Comment by Zanepin** [comment]
> 是的，重名了。项目里有一个名称是parser的文件夹，我之前用pycharm运行的，所以没报错。需要修改下文件夹名及相关引用。

请问一下我该如何操作呢，修改哪几个文件名？
或者在pycharm的命令行里操作就行了（我刚刚是在CMD里操作的）

**Comment by xll-1994** [comment]
我上传了修改后的代码，现在已经可以在命令行运行了。

**Comment by Zanepin** [comment]
非常感谢大佬的及时更新，目前命令行能够运行。
补充一下virtualenv的退出指令：
env\Scripts\deactivate.bat  # Windows
deactivate  # Mac OS
#如果安装失败
pip3 install -r requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

**Comment by xll-1994** [comment]
哈哈哈哈，并不是大佬。
感谢补充~~~
