### ISSUE TITLE
Exception in thread thread_01/02:

### ISSUE THREAD

**Issue by Zanepin** [xll-1994/Spider-Collection#2]
Exception in thread thread_02:
Traceback (most recent call last):
 File "c:\users\..\anaconda3\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
…
OSError: [Errno 22] Invalid argument: 'data/answer.xls'
运行过程中 有时某一线程会报错断开，
断开后以单线程运行至结束。
可能是函数参数的定义问题导致的。

**Comment by xll-1994** [comment]
看样子涉及了三个问题。

第一个问题：准备写入的数据字段的值太长了，抛出了下面这个错误中断了某个线程。
```
Exception: String longer than 32767 characters
```
我之前用xlwt来向excel写数据，现在换成openpyxl已经解决了这个问题。

第二个问题：当线程中断后如何重启？解决思路是每隔一段时间判断下是否有线程被中断，若某个线程被中断了就重新启动。

第三个问题：多线程向excel写数据，任务完成后，excel中数据可能会少于实际数据量，原因可能是多个线程同时打开了excel并向里面写入数据，但只有一个数据被成功保存下来了。解决思路是先将多线程获得的数据存入某个容器，然后用单线程写入。

**Comment by Zanepin** [comment]
>最新的包似乎遗漏了requirements.txt文件。
>我使用了旧版本文件+安装 openpyxl后可以在命令行中启动，
运行后出现了如下问题（使用proxypool的情况下）：
...
2022-01-08 22:29:27 WARNING 访问 https://www.zhihu.com/api/v4/questions/3*******/answers?offset=20&limit=20 发生未知错误，正在重新连接！
2022-01-08 22:29:31 INFO 正在采集ID为 3******* 的问题的第 40 到 60 个回答ID
2022-01-08 22:29:32 WARNING 访问 https://www.zhihu.com/api/v4/questions/3*******/answers?offset=40&limit=20 发生未知错误，正在重新连接！
....

**Comment by Zanepin** [comment]
最新的包似乎遗漏了requirements.txt文件。
我使用了旧版本文件+安装 openpyxl后可以在命令行中启动，
运行后出现了如下问题（使用proxypool的情况下）：
```
...
2022-01-08 22:29:27 WARNING 访问 https://www.zhihu.com/api/v4/questions/3*******/answers?offset=20&limit=20 发生未知错误，正在重新连接！
2022-01-08 22:29:31 INFO 正在采集ID为 3******* 的问题的第 40 到 60 个回答ID
2022-01-08 22:29:32 WARNING 访问 https://www.zhihu.com/api/v4/questions/3*******/answers?offset=40&limit=20 发生未知错误，正在重新连接！
....
```

**Comment by Zanepin** [comment]
上述的问题是被站点封ip导致的拒绝访问错误，可能因为proxypool的ip封禁的问题。
在使用可以正常访问的ip的情况下，
运行过程中未报错双线程交替写入，
输出到xls，爬取一个有88条回答的问题，收回的条数为49条/18条，收回的条数仍然存在问题。

**Comment by xll-1994** [comment]
requirements.txt已上传，第三个问题已修复，第二个问题还没改。

**Comment by xll-1994** [comment]
免费代理质量比较差，被重定向到302页面的几率比较大。我把proxypool中的验证代理网站的地址改成了https://www.zhihu.com/explore 来保证存入redis的代理的质量。

**Comment by xll-1994** [comment]
这些WARNING可以不用管，按我代码里写的，每次出错之后，程序都会将代理从redis中删除，然后再换个代理来访问出错的链接。

**Comment by Zanepin** [comment]
非常感谢你的修复。
测试了几组回答数在400条+的问题。
运行后收回的采集条数符合当前问题的回答条数，过程未报错。
但出现了此问题：一些项的answer_content_tree和answer_content中内容出现缺失（跟文本长度无关），通常是两者其中一项缺失中间到结尾处的文本。
例如：
- answer_content_tree
`<span class="RichText ztext CopyrightRichText-richText css-hnrfcf" options="[object Object]" itemprop="text"><h2>看来很多河南很多人受灾，很是心痛！ 我收入也不是很高，想拿出一个月的收入来捐款，但是老婆意见比较大，怎么办？</h2><p data-pid="Hy5fcbva">因为我平时的工资都是给老婆***</p><p data-pid="NRV6QgGQ">但***</p><p data-pid="K34Wb8aC">还***</p><p data-pid="A-utMcse">钱***</p><p data-pid="I_vNK3DC"><b>有***</b></p><p/></span>`
- answer_content
`看来很多河南很多人受灾，很是心痛！ 我收入也不是很高，想拿出一个月的收入来捐款，但是老婆意见比较大，怎么办？因为我`

**Comment by xll-1994** [comment]
说的是下面这种情况吗？

期待的answer_content中的内容：

看来很多河南很多人受灾，很是心痛！ 我收入也不是很高，想拿出一个月的收入来捐款，但是老婆意见比较大，怎么办？因为我平时的工资都是给老婆掌管的，现在生活的水平也是一般般，就是看见很多感人的画面，自己也想出一份力量给社会，帮助到更多的人。但是老婆说，自己家的生活还是一般般，捐几百就行了，想捐一个月的收入，不肯松口，请大家给点建议，如何说服老婆？真的很想出一份力，为社会做点事情！还有一个问题，我发现微信上有捐款的入口，如果在这里捐进去，钱的去向，用途，可否查询到？钱虽然不是很多，但是至少自己出钱出力了，用在什么地方，总想心里有个底，毕竟以前看过很多类似的新闻了，钱都不懂跑哪里去了，对此比较担心！有捐款经验的兄弟，麻烦给点意见，让我这个小小爱心，传递下去！！！

实际获取的answer_content的内容：

看来很多河南很多人受灾，很是心痛！ 我收入也不是很高，想拿出一个月的收入来捐款，但是老婆意见比较大，怎么办？因为我

我在mac上试的，获取的数据中并没有出现这个问题。

还是说你指的是其它问题？

**Comment by Zanepin** [comment]
是你所说的情况。
有时是answer_content_tree内容缺失，answer_content内容完整。
我重复爬取了一下这个问题，发现每次出现的问题的项是不一样的，偶尔会出现几次，出现次数不多，很奇怪。
这是标记了问题的结果，如果你方便的话可以看看：share.weiyun.com/DJuIHzP8

我现在换到mac上尝试运行，没有用过mac环境code还在折腾proxy_pool中，还没成功..。

**Comment by xll-1994** [comment]
如果是这个问题的话，我也没弄明白为什么会出现这种状况。

answer_content是基于answer_content_tree的内容而产生的。如果answer_content被正常输出了，那意味answer_content_tree也被正常输出了，理论上不会出现你说的这种情况（answer_content_tree内容缺失，answer_content内容完整），因此问题应该不是发生在数据产生阶段。

所以问题出在数据传递阶段或数据保存阶段？

假设数据在传递阶段出错了，那么同一份出错的数据应该在每一次试验中都会出错，也就是输出的数据应该是一样的，显然这不符合现状（每次出现问题的数据项不一样）。

那在我看来，问题只能出在数据保存阶段，可能openpyxl在操作Excel时出错了？但是当我连续多次（每次传入100条数据）让Excel保存你提供的出错的数据时，问题一直都没有复现...

我还没想到其它可能会出问题的地方，回头再研究研究~

**Comment by Zanepin** [comment]
我似乎解决了这个问题。
我在昨天及之前的每一次命令行执行`python main.py answer_spider`之前
都会先执行`env\Scripts\activate`
就是后续执行就成了`(env)C:\..\ZhiHu-Spider>python main.py answer_spider`
今天我忘记了，直接`C:\..\ZhiHu-Spider>python main.py answer_spider`
然后跑出来的结果就没有数据丢失的问题了，这难道是因为重复activate吗...

**Comment by Zanepin** [comment]
另外想问下库主有兴趣写一下爬取知乎文章的功能吗，根据想爬的id`45XXXXXXXX`爬取`zhuanlan.zhihu.com/p/45XXXXXXXX`的文章内容、点赞数、发布时间。
以我的能力恐怕实现不了QAQ，这将对我有很大的帮助，谢谢！

**Comment by xll-1994** [comment]
解决了就好哈~
新功能我回头加下好了，不过具体时间就没准了
着急的话，可以先看看其它人的项目能不能解决需求

**Comment by xll-1994** [comment]
该功能已上线~

**Comment by Zanepin** [comment]
好快！
非常感谢你的帮助。

**Comment by xll-1994** [comment]
不客气~
合作愉快~

**Comment by Zanepin** [comment]
测试后正常运行。
我觉得可以加入读取txt列表的批量采集的命令以提高效率，就不pull request了，我构想的思路如下：
```
import re
#main.py 新命令aritcle_spider2
@cli.command(name='article_spider2')
def article_spider2():
    #读取article.txt
    f=open('article.txt',encoding='utf-8')
    article_txt=f.read()
    article_list=re.findall('(\d{8,10})', article_txt)
    article_list=list(map(eval,article_list))
    print('要采集的文章ID：', article_list)
    f.close()
    for i in range(len(article_list)): 
        start_article_spider(article_id[i])
    print('task is over')
```
另外，可以查看一下你的知乎私信。

**Comment by xll-1994** [comment]
好哒~
感谢你提供的思路~
